apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    {{- include "student-api.labels" . | nindent 4 }}
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: studentdb

