apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: student-api
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: studentdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      nodeSelector:
        type: application
      initContainers:
        - name: migrate-db
          image: dipakrasal2009/sre_bootcamp-api1:v27
          command: ["python", "-m", "app.migrate"]
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: api-config
      containers:
        - name: flask-api
          image: dipakrasal2009/sre_bootcamp-api1:v27
          ports:
            - containerPort: 5050
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: api-config
---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
    - port: 80
      targetPort: 5050

