version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d app_db"]
      interval: 5s
      retries: 5
      start_period: 10s

  api1:
    image: dipakrasal2009/sre_bootcamp3-api1
    ports:
    - "5001:5000"
    container_name: api1
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: app_db
    depends_on:
      - db
    expose:
      - "8081"

  api2:
    image: dipakrasal2009/sre_bootcamp3-api2
    ports:
    - "5002:5000"
    container_name: api2
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: app_db
    depends_on:
      - db
    expose:
      - "8081"

  nginx:
    image: dipakrasal2009/nginx:latest
    container_name: nginx
    ports:
      - "7070:60"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2

volumes:
  pgdata:

